DROP DATABASE javatraining;
CREATE DATABASE javatraining CHARACTER SET UTF8;
USE javatraining;

CREATE TABLE BOOK_INFO(
    PROD_ID INT(10) AUTO_INCREMENT NOT NULL, 
    BOOK_NAME VARCHAR(30) NOT NULL,
    AUTHOR VARCHAR(30) NOT NULL,
    AMOUNT INT(10) NOT NULL,
    LOCATION VARCHAR(30) NOT NULL,
    DESCRIPTION VARCHAR(100),
    PRIMARY KEY (PROD_ID)
    );

CREATE TABLE USERS(
    USER_ID INT(10) AUTO_INCREMENT NOT NULL, 
    USER_NAME VARCHAR(30) NOT NULL,
    USER_PASSWORD VARCHAR(30) NOT NULL,
    PRIMARY KEY (USER_ID)
    );
    
CREATE TABLE COMMUNITIES(
	COMMUNITY_ID INT(10) AUTO_INCREMENT NOT NULL, 
    COMMUNITY_NAME VARCHAR(30) NOT NULL,
    COMMUNITY_PASSWORD VARCHAR(30) NOT NULL,
    PRIMARY KEY (COMMUNITY_ID)
    );

INSERT INTO USERS VALUE(1,"Machida","muit123");
INSERT INTO USERS VALUE(2,"Suzuki","suzuki");
INSERT INTO USERS VALUE(3,"Ozaki","ozaki");

INSERT INTO BOOK_INFO VALUE(1,"Java Training","Hoge Taro","10","Tokyo","Java Training");
INSERT INTO BOOK_INFO VALUE(2,"金融業界のトレンド","M社","5","Osaka","Finance");

INSERT INTO COMMUNITIES VALUE(1,"りんご","apple");
INSERT INTO COMMUNITIES VALUE(2,"ばなな","banana");
INSERT INTO COMMUNITIES VALUE(3,"れもん","lemon");