DROP DATABASE training;
DROP DATABASE javatraining;
CREATE DATABASE javatraining CHARACTER SET UTF8;
USE javatraining;

CREATE TABLE BOOK_INFO(
    PROD_ID INT(10) AUTO_INCREMENT NOT NULL, 
    BOOK_NAME VARCHAR(30) NOT NULL,
    AUTHOR VARCHAR(30) NOT NULL,
    AMOUNT INT(10) NOT NULL,
    LOCATION VARCHAR(30) NOT NULL,
    DESCRIPTION VARCHAR(100),
    PRIMARY KEY (PROD_ID)
    );

CREATE TABLE USER_MASTER(
    USER_ID INT(10) AUTO_INCREMENT NOT NULL, 
    USER_NAME VARCHAR(30) NOT NULL,
    PASSWORD VARCHAR(30) NOT NULL,
    PRIMARY KEY (USER_ID)
    );

INSERT INTO USER_MASTER VALUE(1,"Machida","itp123");
INSERT INTO USER_MASTER VALUE(2,"Suzuki","suzuki");
INSERT INTO USER_MASTER VALUE(3,"Ozaki","ozaki");

INSERT INTO BOOK_INFO VALUE(1,"Java Training","Hoge Taro","10","Tokyo","Java Training");
INSERT INTO BOOK_INFO VALUE(2,"Finance","Hoge Jiro","5","Osaka","Finance");